// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYEd89UI16VyYuM2F3D90_41mwJCZHU94',
    appId: '1:357055052387:web:935f4e12ce2558f1929656',
    messagingSenderId: '357055052387',
    projectId: 'health-care-a85f5',
    authDomain: 'health-care-a85f5.firebaseapp.com',
    storageBucket: 'health-care-a85f5.firebasestorage.app',
    measurementId: 'G-82NDX9CCPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqzgAi64GAYpZZ_pkEwriIV4-RFuYEgWM',
    appId: '1:357055052387:android:3ca405edbbe269ed929656',
    messagingSenderId: '357055052387',
    projectId: 'health-care-a85f5',
    storageBucket: 'health-care-a85f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Izb1lnNeHyL7uWw15WmJevTrTJQRDU0',
    appId: '1:357055052387:ios:56f94515ebff5dfc929656',
    messagingSenderId: '357055052387',
    projectId: 'health-care-a85f5',
    storageBucket: 'health-care-a85f5.firebasestorage.app',
    iosBundleId: 'com.example.healthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2Izb1lnNeHyL7uWw15WmJevTrTJQRDU0',
    appId: '1:357055052387:ios:56f94515ebff5dfc929656',
    messagingSenderId: '357055052387',
    projectId: 'health-care-a85f5',
    storageBucket: 'health-care-a85f5.firebasestorage.app',
    iosBundleId: 'com.example.healthcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYEd89UI16VyYuM2F3D90_41mwJCZHU94',
    appId: '1:357055052387:web:a91be46bb6f6c1d0929656',
    messagingSenderId: '357055052387',
    projectId: 'health-care-a85f5',
    authDomain: 'health-care-a85f5.firebaseapp.com',
    storageBucket: 'health-care-a85f5.firebasestorage.app',
    measurementId: 'G-YLN0Q9D0BF',
  );

}
